### ISSUE TITLE
Add splitter interface for use with sklearn

### ISSUE THREAD

**Issue by leogott** [glaserL/glassplitter#4]
The TF-IDF Vectorizer expects a function/callable with the signature
`str -> list[str]`
I request a function (let's call it tokenize_flat or something) that expects a list/iterable of strings (instead of tuples) and returns a list/iterable of strings. (instead of a nested list of enumerated strings)

My kinda messy workaround for reference:
```python
tokenizer = Tokenizer(lang="en", clean=True, doc_type="pdf")

def tokenize_only(tokenizer: Tokenizer, text_boxes):
    """Tokenize text-boxes."""
    spans = ((item["text"], i) for i, item in enumerate(text_boxes))
    sentence_list = tokenizer.split(spans, trim=True)

    for sentence in sentence_list:
        yield [a for a, i in sentence]

def tokenizer_wrapped(tokenizer: Tokenizer) -> Callable:
    def tokenize(arg: str):
        return list(reduce(operator.add, tokenize_only(tokenizer, arg)))
    return tokenize

# print("Vectorizing %d documents..." % len(data))
tfidf_vectorizer = TfidfVectorizer(
    max_df=0.5, # Percentage of docs
    min_df=3, # Absolute number of docs to contain feature (word)
    max_features=5000,
    use_idf=True,
    sublinear_tf=True,
    preprocessor=lambda x: x, #HACK
    tokenizer=tokenizer_wrapped(tokenizer),
    # tokenizer=str.split,
    token_pattern=None,
    stop_words="english",
    ngram_range=(1, 2),
)
```

**Comment by glaserL** [comment]
I am not certain I understand your request, consider the example in the readme:

```python
spans = [("I am a ", {"line": 1}), ("split sentence!", {"line": 2})]
tokenizer = Tokenizer(lang="en", clean=True, doc_type="pdf")

split = tokenizer.split(spans, trim=True)
# [[("", 0), ("I", 0), ("am", 0), ("a", 0), ("split", 1), ("sentence", 1), ("!", 1), ("", 1)]]
```
would the modification look like this?
```python
spans = ["I am a ", "split sentence!"]
tokenizer = Tokenizer(lang="en", clean=True, doc_type="pdf")

split = tokenizer.split_flat(spans, trim=True)
# [[("", "I", "am", "a", "split", "sentence", "!", ""], [#next sentence]]
```

Or should all spans be collected in a single list?

**Comment by leogott** [comment]
So what I mean was the following:
`["I am a sentence.", "And the next one."] -> ["I", "am", "a", "sentence", ".",  "", "And", "the", "next", "one", "."]`
Signature: list[str] -> list[str]

But converting from list[list[str]] to list[str] is trivial, just a functools.reduce(operator.add, our_list).


~~I just noticed a problem though. It seems like the tfidf-vectorizer expects one string per *document*? Will have to verify that first thing tomorrow.~~ Tf-idf-vectorizer *with default preprocessor and tokenizer* expects one string per document. But it doesn't care as long as the tokenizer spits out a list (or probably just iterable) over strings to be interpreted as features.
